### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by SheepCommander** [SammCheese/invisible-chat#9]
![image](https://user-images.githubusercontent.com/66646514/148683790-995e1bff-89af-4042-8f69-e679d3b24e26.png)
![image](https://user-images.githubusercontent.com/66646514/148683794-397ec270-d5ce-45eb-973e-e7d422c150d4.png)

**Comment by SammCheese** [comment]
Fixed

**Comment by SheepCommander** [comment]
I'm afraid I still don't see it after `git pull`

![image](https://user-images.githubusercontent.com/66646514/148723627-e4623525-b98c-4788-8487-d49406c2aed7.png)
![image](https://user-images.githubusercontent.com/66646514/148723665-907d87ca-2db9-4cab-ac89-7cbeddc6060e.png)

**Comment by SammCheese** [comment]
It seems to work for me in the current state. maybe reinstall?

**Comment by SheepCommander** [comment]
yeah still dont

(it's actually win11)
![image](https://user-images.githubusercontent.com/66646514/148726118-2a1dc5ad-2d5f-4277-a33c-0c2c566a76c0.png)
![image](https://user-images.githubusercontent.com/66646514/148726210-8662e2f9-8c2e-4d8c-8c08-323aadd3af6d.png)
![image](https://user-images.githubusercontent.com/66646514/148726222-5f654842-9af7-4621-8123-9a6b1d5c4d58.png)

**Comment by SammCheese** [comment]
odd
